@startuml Patron Command

Invoker -> commandMain
commandMain -> Stock
class commandMain{}

Invoker -> Command
class Invoker{

    - comandList

    + takeOrder(order)
    + placeOrder()
}


class Stock{
        
    - name: String
    - quantity: int

    + getName()
    + setName(name)
    + getQuantity()
    + setQuantity(quantity)
    + buy()
}

interface Command{
        + execute()
}

class Buy implements Command{
    
    - stock: Stock

    + Buy(stock)
    + execute()
}

@enduml